version: '3'

services:
  db:
    image: mysql:8.0.30-debian
    ports:
      - "3307:3306"  # Mapeia a porta 3306 do contêiner para a porta 3307 da máquina local
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nest
